'use strict';
const fs = require('fs');
const path = require('path');

function buildPublic(root) {
    root = path.resolve(root);
    const output = path.resolve(root, 'public');
    const marker = path.join(output, '.schedule-generated');
    if (path.dirname(output) !== root || path.basename(output) !== 'public') throw Error('Invalid output directory');
    if (fs.existsSync(output)) {
        if (fs.lstatSync(output).isSymbolicLink() || !fs.existsSync(marker)) {
            throw Error('Refusing to replace an unmanaged public directory');
        }
        // Only this explicitly marked, generated directory may be replaced.
        fs.rmSync(output, { recursive: true });
    }
    fs.mkdirSync(output);
    fs.writeFileSync(marker, 'Generated by scripts/build-public.js; do not edit.\n');
    const copy = relative => {
        const source = path.join(root, relative);
        const destination = path.join(output, relative);
        if (fs.lstatSync(source).isSymbolicLink()) throw Error(`Unexpected symlink: ${relative}`);
        if (fs.statSync(source).isDirectory()) {
            fs.mkdirSync(destination, { recursive: true });
            fs.readdirSync(source).forEach(name => copy(path.join(relative, name)));
        } else {
            fs.mkdirSync(path.dirname(destination), { recursive: true });
            fs.copyFileSync(source, destination);
        }
    };
    fs.readdirSync(root).filter(name => name.endsWith('.html')).forEach(copy);
    ['sw.js', 'js', 'css', 'data/demo-schedule.json', 'data/session-2025-26.json', 'data/links.json',
        'legacy', 'docs/print'].forEach(copy);
    return output;
}

if (require.main === module) console.log(`Static output: ${buildPublic(path.join(__dirname, '..'))}`);
module.exports = { buildPublic };
